const DATA=window.__SEASON_PRICE_DATA__;
const BRAND_ORDER=["Fysea","Oneup","THE BLENDER","tbh家居（THE BEAST）","Ubras家居服","Almondrocks","gelato pique","AAAD / an action a day","TWOI Design Lab","Victoria's Secret 维多利亚的秘密","MUJI 无印良品","Zara Home"];
const CATEGORY_ORDER=["背心吊带-单件","背心吊带-多件/套装","T恤","内裤","裤装-短裤","裤装-长裤","衬衫-长袖","家居服-上装","家居服-裤装","家居服-套装","眼罩"];
const SEASON_ORDER=["春季","夏季","秋季","冬季"];
const MONTH_ORDER=["9月","10月","11月"];
const SIGNAL_ORDER=["秋季上新","长袖上装","轻薄长裤","薄绒/法兰绒","羊毛层搭","明确月份"];
const state={season:"全部季节",month:"全部月份",signal:"全部线索",brand:"全部品牌",category:"全部品类",price:"全部",search:"",mode:"month"};
const $=(id)=>document.getElementById(id);
function esc(v){return String(v==null?"":v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;")}
function num(v){return Number.isFinite(v)?Math.round(v).toLocaleString("zh-CN"):"—"}
function money(v){return Number.isFinite(v)?"¥"+Math.round(v).toLocaleString("zh-CN"):"—"}
function pct(n,d){return d?Math.round(n/d*1000)/10+"%":"0%"}
function priceRange(s){return Number.isFinite(s.p25)&&Number.isFinite(s.p75)?money(s.p25)+"-"+money(s.p75):"无价格样本"}
function picture(r){if(!r.localImageWebp&&!r.localImageAvif)return '<div class="no-img">无本地图片</div>';return '<picture>'+(r.localImageAvif?'<source srcset="'+esc(r.localImageAvif)+'" type="image/avif">':"")+(r.localImageWebp?'<source srcset="'+esc(r.localImageWebp)+'" type="image/webp">':"")+'<img src="'+esc(r.localImageWebp||r.localImageAvif)+'" alt="'+esc(r.title)+'" loading="lazy"></picture>'}
function score(r){if(Number.isFinite(r.sales))return 1000000000+r.sales;if(Number.isFinite(r.rank))return 500000-r.rank;if(Number.isFinite(r.price))return r.price;return 0}
function percentile(values,p){const nums=values.filter(Number.isFinite).sort((a,b)=>a-b);if(!nums.length)return null;const idx=(nums.length-1)*p;const lo=Math.floor(idx);const hi=Math.ceil(idx);return lo===hi?nums[lo]:nums[lo]+(nums[hi]-nums[lo])*(idx-lo)}
function band(rows){const prices=rows.map(r=>r.price).filter(Number.isFinite);if(!prices.length)return{min:null,p25:null,median:null,p75:null,max:null,avg:null};return{min:Math.min(...prices),p25:percentile(prices,.25),median:percentile(prices,.5),p75:percentile(prices,.75),max:Math.max(...prices),avg:prices.reduce((a,b)=>a+b,0)/prices.length}}
function buildStat(rows,extra){const priced=rows.filter(r=>Number.isFinite(r.price));const sales=rows.filter(r=>Number.isFinite(r.sales));const b=band(rows);const top=[...rows].sort((a,b)=>score(b)-score(a))[0]||{};return Object.assign({},extra,{skuCount:rows.length,pricedCount:priced.length,priceCoverage:pct(priced.length,rows.length),min:b.min,p25:b.p25,median:b.median,p75:b.p75,max:b.max,avg:b.avg,salesKnownCount:sales.length,totalSalesLower:sales.length?sales.reduce((s,r)=>s+r.sales,0):null,topProduct:top.title||"",topSalesLower:Number.isFinite(top.sales)?top.sales:null})}
function filtered(){const q=state.search.trim().toLowerCase();return DATA.rows.filter(r=>{if(state.season!=="全部季节"&&!r.seasons.includes(state.season))return false;if(state.month!=="全部月份"&&r.focusMonth!==state.month)return false;if(state.signal!=="全部线索"&&!r.focusTags.includes(state.signal))return false;if(state.brand!=="全部品牌"&&r.brand!==state.brand)return false;if(state.category!=="全部品类"&&r.category!==state.category)return false;if(state.price==="有价格"&&!Number.isFinite(r.price))return false;if(state.price==="缺价格"&&Number.isFinite(r.price))return false;if(!q)return true;return (r.brand+" "+r.category+" "+r.title+" "+r.seriesName+" "+r.skuSummary+" "+r.itemId).toLowerCase().includes(q)})}
function setOptions(){ $("seasonFilter").innerHTML=["全部季节",...SEASON_ORDER].map(v=>'<option '+(v===state.season?'selected':'')+'>'+esc(v)+'</option>').join("");$("monthFilter").innerHTML=["全部月份",...MONTH_ORDER].map(v=>'<option>'+esc(v)+'</option>').join("");$("signalFilter").innerHTML=["全部线索",...SIGNAL_ORDER].map(v=>'<option>'+esc(v)+'</option>').join("");$("brandFilter").innerHTML=["全部品牌",...BRAND_ORDER].map(v=>'<option>'+esc(v)+'</option>').join("");$("categoryFilter").innerHTML=["全部品类",...CATEGORY_ORDER].map(v=>'<option>'+esc(v)+'</option>').join("")}
function bind(){["season","month","signal","brand","category","price"].forEach(k=>{$(k+"Filter").onchange=e=>{state[k]=e.target.value;render()}});$("searchInput").oninput=e=>{state.search=e.target.value;render()};document.querySelectorAll(".analysis-tabs button").forEach(btn=>btn.onclick=()=>{state.mode=btn.dataset.mode;document.querySelectorAll(".analysis-tabs button").forEach(b=>b.classList.toggle("active",b===btn));renderStatsTable(filtered())})}
function renderMethod(){const m=DATA.metrics;$("totalRows").textContent=num(m.totalRows);$("methodText").textContent="现有数据没有结构化发布时间字段；标题中明确出现9/10/11月的SKU为 "+num(m.exactMonthCount)+" 条。本页按标题、系列名、SKU摘要和品类信号推断月份：9月看早秋过渡/长袖/轻薄长裤，10月看羊毛/针织/薄绒层搭，11月看保暖/加厚/冬季信号。"}
function renderSummary(rows){const priced=rows.filter(r=>Number.isFinite(r.price)).length;const exact=rows.filter(r=>r.exactMonths.length).length;const images=rows.filter(r=>r.localImageWebp||r.localImageAvif).length;const bandNow=band(rows);const monthRows=rows.filter(r=>r.focusMonth).length;$("summary").innerHTML=[["当前SKU",num(rows.length),"筛选条件命中"],["价格覆盖",pct(priced,rows.length),num(priced)+" 条有价格"],["主价格带",priceRange(bandNow),"P25-P75，中位 "+money(bandNow.median)],["9-11月桶",num(monthRows),exact?num(exact)+" 条明确月份":"无明确月份"],["本地图片",pct(images,rows.length),num(images)+" 张 WebP/AVIF"]].map(([a,b,c])=>'<div class="stat"><span>'+a+'</span><strong>'+b+'</strong><em>'+c+'</em></div>').join("")}
function topCategories(rows){const map=new Map();rows.forEach(r=>{const key=r.category;map.set(key,(map.get(key)||0)+1)});return [...map.entries()].sort((a,b)=>b[1]-a[1]).slice(0,4)}
function renderLanes(){const maxSeason=Math.max(...DATA.seasonOverview.map(s=>s.skuCount),1);$("seasonOverview").innerHTML=DATA.seasonOverview.map(s=>{const cats=topCategories(DATA.rows.filter(r=>r.seasons.includes(s.season)));return '<article class="lane"><h3>'+s.season+'</h3><div class="range">'+priceRange(s)+'</div><small>SKU '+num(s.skuCount)+'，价格覆盖 '+s.priceCoverage+'，中位 '+money(s.median)+'</small><div class="mini-bars">'+cats.map(([c,n])=>'<div class="mini-row"><span>'+esc(c)+'</span><div class="bar"><i style="width:'+Math.max(6,n/maxSeason*100)+'%"></i></div><b>'+num(n)+'</b></div>').join("")+'</div></article>'}).join("");
const maxMonth=Math.max(...DATA.monthOverview.map(s=>s.skuCount),1);$("monthOverview").innerHTML=DATA.monthOverview.map(s=>{const rows=DATA.rows.filter(r=>r.focusMonth===s.month);const cats=topCategories(rows);return '<article class="lane"><h3>'+s.month+'</h3><div class="range">'+priceRange(s)+'</div><small>SKU '+num(s.skuCount)+'，价格覆盖 '+s.priceCoverage+'。'+(s.month==="9月"?"早秋过渡":s.month==="10月"?"层搭加温":"入冬保暖")+'</small><div class="mini-bars">'+cats.map(([c,n])=>'<div class="mini-row"><span>'+esc(c)+'</span><div class="bar"><i style="width:'+Math.max(6,n/maxMonth*100)+'%"></i></div><b>'+num(n)+'</b></div>').join("")+'</div></article>'}).join("")}
function groupedStats(rows){const map=new Map();function add(parts,row){const key=parts.join("\u0000");if(!map.has(key))map.set(key,{parts,rows:[]});map.get(key).rows.push(row)}rows.forEach(r=>{if(state.mode==="season"){r.seasons.forEach(s=>add([s,r.brand,r.category],r))}else if(state.mode==="signal"){r.focusTags.forEach(t=>add([t,r.brand,r.category],r))}else if(r.focusMonth){add([r.focusMonth,r.brand,r.category],r)}});let out=[...map.values()].map(g=>buildStat(g.rows,{a:g.parts[0],brand:g.parts[1],category:g.parts[2]}));const order=state.mode==="season"?SEASON_ORDER:state.mode==="signal"?SIGNAL_ORDER:MONTH_ORDER;out.sort((x,y)=>order.indexOf(x.a)-order.indexOf(y.a)||BRAND_ORDER.indexOf(x.brand)-BRAND_ORDER.indexOf(y.brand)||CATEGORY_ORDER.indexOf(x.category)-CATEGORY_ORDER.indexOf(y.category));return out}
function renderStatsTable(rows){const stats=groupedStats(rows);const first=state.mode==="season"?"季节":state.mode==="signal"?"线索":"月份";$("statsTable").innerHTML='<thead><tr><th>'+first+'</th><th>品牌</th><th>品类</th><th class="num">SKU</th><th class="num">有价格</th><th>价格覆盖</th><th class="num">最低</th><th class="num">P25</th><th class="num">中位</th><th class="num">P75</th><th class="num">最高</th><th class="num">销量下限</th><th>代表商品</th></tr></thead><tbody>'+stats.map(s=>'<tr><td>'+esc(s.a)+'</td><td>'+esc(s.brand)+'</td><td>'+esc(s.category)+'</td><td class="num">'+num(s.skuCount)+'</td><td class="num">'+num(s.pricedCount)+'</td><td>'+s.priceCoverage+'</td><td class="num">'+money(s.min)+'</td><td class="num price-band">'+money(s.p25)+'</td><td class="num price-band">'+money(s.median)+'</td><td class="num price-band">'+money(s.p75)+'</td><td class="num">'+money(s.max)+'</td><td class="num">'+num(s.totalSalesLower)+'</td><td>'+esc(s.topProduct)+'</td></tr>').join("")+'</tbody>'}
function productCard(r){return '<article class="product">'+picture(r)+'<div><h3>'+esc(r.title)+'</h3><div class="chips"><span class="chip">'+esc(r.brand)+'</span><span class="chip">'+esc(r.category)+'</span><span class="chip">'+(r.focusMonth||"无月份桶")+'</span><span class="chip">'+money(r.price)+'</span></div><small>季节：'+(r.seasons.length?r.seasons.join("、"):"未判定")+'<br>线索：'+(r.focusTags.length?r.focusTags.join("、"):"无")+'<br>销量：'+(r.salesText||num(r.sales))+' ｜ 系列：'+(r.seriesName||"未识别")+'</small><div class="links">'+(r.productUrl?'<a href="'+esc(r.productUrl)+'" target="_blank">商品链接</a>':'<span class="muted">链接缺失</span>')+'</div></div></article>'}
function renderProducts(rows){const sorted=[...rows].sort((a,b)=>score(b)-score(a));$("productNote").textContent="展示当前筛选命中的全部 "+num(sorted.length)+" 条 SKU，图片只使用 fuzhuang10 本地 assets/images 里的 AVIF/WebP。";$("productGrid").innerHTML=sorted.map(productCard).join("")||'<p class="muted">没有匹配的SKU。</p>'}
function render(){const rows=filtered();renderSummary(rows);renderStatsTable(rows);renderProducts(rows)}
setOptions();bind();renderMethod();renderLanes();render();