const DATA=window.__SALES_TOP10_DATA__;
const state={brand:"全部品牌"};
const $=id=>document.getElementById(id);
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;")}
function money(v){return Number.isFinite(v)?"¥"+Math.round(v).toLocaleString("zh-CN"):"—"}
function num(v){return Number.isFinite(v)?Math.round(v).toLocaleString("zh-CN"):"—"}
function pct(n,d){return d?Math.round(n/d*100)+"%":"—"}
function priceBand(p){return p.pricedCount?money(p.p25)+"-"+money(p.p75):"—"}
function init(){ $("generatedAt").textContent=DATA.generatedAtText; $("brandCount").textContent=DATA.summary.brandCount; $("brandFilter").innerHTML=["全部品牌",...DATA.brands.map(b=>b.brand)].map(v=>`<option>${esc(v)}</option>`).join(""); $("brandFilter").onchange=e=>{state.brand=e.target.value;render()}; render(); }
function visibleBrands(){return DATA.brands.filter(b=>state.brand==="全部品牌"||b.brand===state.brand)}
function renderSummary(brands){const rows=brands.flatMap(b=>b.topRows);const withSales=rows.filter(r=>Number.isFinite(r.salesParsed)).length;const withPrice=rows.filter(r=>Number.isFinite(r.price)).length;const ipRows=rows.filter(r=>r.reasonTags.includes("联名/IP")||r.reasonTags.includes("明星同款")).length;$("summaryGrid").innerHTML=[["品牌数",num(brands.length),"当前筛选"],["TOP商品",num(rows.length),"每品牌至多10款"],["有销量字段",pct(withSales,rows.length),num(withSales)+" 款"],["有价格",pct(withPrice,rows.length),num(withPrice)+" 款"],["IP/明星款",num(ipRows),"标题命中"]].map(([a,b,c])=>`<div class=stat><span>${a}</span><strong>${b}</strong><em>${c}</em></div>`).join("")}
function renderNav(){ $("brandNav").innerHTML=["全部品牌",...DATA.brands.map(b=>b.brand)].map(name=>`<button class="${state.brand===name?"active":""}" data-brand="${esc(name)}">${esc(name)}</button>`).join(""); $("brandNav").querySelectorAll("button").forEach(btn=>btn.onclick=()=>{state.brand=btn.dataset.brand;$("brandFilter").value=state.brand;render()}) }
function imageHtml(row){if(!row.image)return '<div class="thumb no-thumb">无图</div>';return `<picture class=thumb>${row.image.avif?`<source srcset="${esc(row.image.avif)}" type="image/avif">`:""}<img src="${esc(row.image.webp||row.image.avif)}" alt="${esc(row.title)}" loading="lazy"></picture>`}
function rowHtml(row){return `<tr><td class=rank>#${row.rank}</td><td class=product-title><div class=product-wrap>${imageHtml(row)}<div><strong>${row.productUrl?`<a href="${esc(row.productUrl)}" target="_blank">${esc(row.title)}</a>`:esc(row.title)}</strong><small>${esc(row.nativeCategory)} ｜ itemId ${esc(row.itemId||"—")}</small></div></div></td><td class=num>${row.salesDisplay||"—"}</td><td class=num>${money(row.price)}</td><td><div class=tags>${row.reasonTags.map(tag=>`<span class=tag>${esc(tag)}</span>`).join("")}</div></td><td class=reason>${esc(row.reasonText)}</td><td class=link-cell>${row.productUrl?`<a href="${esc(row.productUrl)}" target="_blank">打开</a>`:"—"}</td></tr>`}
function brandHtml(brand){const salesCoverage=brand.rowCount?pct(brand.salesRows,brand.rowCount):"—";return `<article class=brand id="${esc(brand.slug)}"><header class=brand-head><div><h2>${esc(brand.brand)}</h2><p>${brand.hasSales?"按前台销量/付款字段排序。":"当前品牌缺少销量/付款字段，下方为采集顺序参考。"} </p></div><div class=head-metrics><div><span>样本SKU</span><strong>${num(brand.rowCount)}</strong></div><div><span>销量字段</span><strong class="${brand.hasSales?"":"warn"}">${salesCoverage}</strong></div><div><span>主力价格带</span><strong>${priceBand(brand.priceBand)}</strong></div></div></header><section class=brand-summary>${esc(brand.summary)}</section><div class=top-table-wrap><table class=top-table><thead><tr><th>排行</th><th>商品</th><th class=num>销量/付款</th><th class=num>价格</th><th>可能驱动</th><th>原因判断</th><th class=link-cell>链接</th></tr></thead><tbody>${brand.topRows.map(rowHtml).join("")}</tbody></table></div></article>`}
function render(){const brands=visibleBrands();renderSummary(brands);renderNav();$("brandList").innerHTML=brands.map(brandHtml).join("")||'<p class=empty>没有匹配的品牌。</p>'}
init();