const DATA=window.__ALL_SKU_DATA__;const BRAND_ORDER=["Fysea","Oneup","THE BLENDER","tbh家居（THE BEAST）","Ubras家居服","Almondrocks","gelato pique","AAAD / an action a day","TWOI Design Lab","Victoria's Secret 维多利亚的秘密","MUJI 无印良品","Zara Home"];const CATEGORY_ORDER=["背心吊带-单件","背心吊带-多件/套装","T恤","内裤","裤装-短裤","裤装-长裤","衬衫-长袖","家居服-上装","家居服-裤装","家居服-套装","眼罩"];const state={brand:"全部品牌",category:"全部品类",price:"全部",image:"全部",search:"",view:"grid"};const $=id=>document.getElementById(id);
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;")}function money(v){return Number.isFinite(v)?"¥"+Math.round(v).toLocaleString("zh-CN"):"—"}function num(v){return Number.isFinite(v)?Math.round(v).toLocaleString("zh-CN"):"—"}
function picture(r,cls=""){if(!r.localImageWebp&&!r.localImageAvif)return "";return `<picture${cls?` class="${cls}"`:""}>${r.localImageAvif?`<source srcset="${esc(r.localImageAvif)}" type="image/avif">`:""}${r.localImageWebp?`<source srcset="${esc(r.localImageWebp)}" type="image/webp">`:""}<img src="${esc(r.localImageWebp||r.localImageAvif)}" alt="${esc(r.title)}" loading="lazy"></picture>`}
function init(){document.title="全部核心 SKU 明细";$("heroCount").textContent=DATA.rows.length.toLocaleString("zh-CN");$("brandFilter").innerHTML=["全部品牌",...BRAND_ORDER].map(v=>`<option>${esc(v)}</option>`).join("");$("categoryFilter").innerHTML=["全部品类",...CATEGORY_ORDER].map(v=>`<option>${esc(v)}</option>`).join("");$("brandFilter").onchange=e=>{state.brand=e.target.value;render()};$("categoryFilter").onchange=e=>{state.category=e.target.value;render()};$("priceFilter").onchange=e=>{state.price=e.target.value;render()};$("imageFilter").onchange=e=>{state.image=e.target.value;render()};$("searchInput").oninput=e=>{state.search=e.target.value;render()};document.querySelectorAll(".segmented button").forEach(b=>b.onclick=()=>{state.view=b.dataset.view;document.querySelectorAll(".segmented button").forEach(x=>x.classList.toggle("active",x===b));render()});render()}
function filtered(){const q=state.search.trim().toLowerCase();return DATA.rows.filter(r=>{if(state.brand!=="全部品牌"&&r.brand!==state.brand)return false;if(state.category!=="全部品类"&&r.category!==state.category)return false;if(state.price==="有价格"&&!Number.isFinite(r.price))return false;if(state.price==="缺价格"&&Number.isFinite(r.price))return false;if(state.image==="有本地图片"&&!r.localImage)return false;if(state.image==="无本地图片"&&r.localImage)return false;if(!q)return true;return `${r.brand} ${r.category} ${r.title} ${r.shopName} ${r.itemId} ${r.skuSummary}`.toLowerCase().includes(q)})}
function renderSummary(rows){const priced=rows.filter(r=>Number.isFinite(r.price)).length;const images=rows.filter(r=>r.localImage).length;const sales=rows.filter(r=>Number.isFinite(r.sales)).length;const links=rows.filter(r=>r.productUrl).length;const brands=new Set(rows.map(r=>r.brand)).size;$("summary").innerHTML=[["筛选后SKU",num(rows.length),"当前条件命中"],["品牌数",num(brands),"涉及品牌"],["有价格",Math.round(priced/(rows.length||1)*100)+"%",num(priced)+" 条"],["有本地图片",Math.round(images/(rows.length||1)*100)+"%",num(images)+" 张"],["有链接",Math.round(links/(rows.length||1)*100)+"%",num(links)+" 条"]].map(([a,b,c])=>`<div class=stat><span>${a}</span><strong>${b}</strong><em>${c}</em></div>`).join("")}
function productCard(r){return `<article class="sku">${r.localImageWebp||r.localImageAvif?picture(r):`<div class="no-img">${r.hasRemoteImage?"图片未下载":"无图"}</div>`}<div><h2>${esc(r.title)}</h2><div class="chips"><span class="chip">${esc(r.brand)}</span><span class="chip">${esc(r.category)}</span><span class="chip">${money(r.price)}</span><span class="chip">${r.salesText?esc(r.salesText):num(r.sales)}</span></div><small>店铺：${esc(r.shopName||"—")} ｜ itemId：${esc(r.itemId||"—")}</small><div class="links">${r.productUrl?`<a href="${esc(r.productUrl)}" target="_blank">商品链接</a>`:"<span>链接缺失</span>"}<a href="#tableView" onclick="window.__jumpToTable && window.__jumpToTable()">表格定位</a></div></div></article>`}
function tableRow(r){return `<tr><td>${r.localImageWebp||r.localImageAvif?picture(r,"thumb-picture"):"—"}</td><td>${esc(r.brand)}</td><td>${esc(r.category)}</td><td>${esc(r.title)}</td><td class=num>${money(r.price)}</td><td>${r.salesText?esc(r.salesText):num(r.sales)}</td><td>${esc(r.shopName||"")}</td><td>${r.productUrl?`<a href="${esc(r.productUrl)}" target="_blank">打开</a>`:"—"}</td><td>${esc(r.itemId||"")}</td><td>${esc(r.skuSummary||"")}</td></tr>`}
function renderList(){const rows=filtered();$("pageInfo").textContent=`已展示 ${num(rows.length)} / 共命中 ${num(rows.length)} 条`;$("gridView").hidden=state.view!=="grid";$("tableView").hidden=state.view!=="table";$("gridView").innerHTML=rows.map(productCard).join("")||"<p>没有匹配的SKU。</p>";$("skuTable").innerHTML=`<thead><tr><th>图</th><th>品牌</th><th>品类</th><th>标题</th><th>价格</th><th>销量</th><th>店铺</th><th>链接</th><th>itemId</th><th>SKU摘要</th></tr></thead><tbody>${rows.map(tableRow).join("")}</tbody>`
}
window.__jumpToTable=()=>{state.view="table";document.querySelectorAll(".segmented button").forEach(b=>b.classList.toggle("active",b.dataset.view==="table"));renderList()};function render(){const rows=filtered();renderSummary(rows);renderList()}init();