const DATA=window.__PRICE_BAND_DATA__;
const state={category:"全部品类",brand:"全部品牌",search:""};
const $=id=>document.getElementById(id);
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;")}
function money(v){return Number.isFinite(v)?"¥"+Math.round(v).toLocaleString("zh-CN"):"—"}
function num(v){return Number.isFinite(v)?Math.round(v).toLocaleString("zh-CN"):"—"}
function pct(v){return Number.isFinite(v)?Math.round(v*100)+"%":"0%"}
function range(row){return Number.isFinite(row.min)?money(row.min)+"-"+money(row.max):"—"}
function init(){document.title="核心品类价格带 · fuzhuang15 分类口径";$("corePricedRows").textContent=num(DATA.summary.corePricedRows);$("categoryFilter").innerHTML=["全部品类",...DATA.categoryOrder].map(v=>`<option>${esc(v)}</option>`).join("");$("brandFilter").innerHTML=["全部品牌",...DATA.brandOrder].map(v=>`<option>${esc(v)}</option>`).join("");$("categoryFilter").onchange=e=>{state.category=e.target.value;render()};$("brandFilter").onchange=e=>{state.brand=e.target.value;render()};$("searchInput").oninput=e=>{state.search=e.target.value;render()};render()}
function categories(){const q=state.search.trim().toLowerCase();return DATA.categories.map(cat=>({...cat,brands:cat.brands.filter(b=>state.brand==="全部品牌"||b.brand===state.brand)})).filter(cat=>{if(state.category!=="全部品类"&&cat.category!==state.category)return false;if(!cat.brands.length)return false;if(!q)return true;return cat.category.toLowerCase().includes(q)||cat.brands.some(b=>b.brand.toLowerCase().includes(q))})}
function renderSummary(cats){const brands=new Set(cats.flatMap(c=>c.brands.map(b=>b.brand))).size;const priced=cats.reduce((sum,c)=>sum+c.brands.reduce((s,b)=>s+b.pricedCount,0),0);const sku=cats.reduce((sum,c)=>sum+c.brands.reduce((s,b)=>s+b.skuCount,0),0);const missing=cats.reduce((sum,c)=>sum+c.brands.reduce((s,b)=>s+b.missingPriceCount,0),0);$("summary").innerHTML=[["品类",num(cats.length),"当前筛选"],["品牌",num(brands),"有样本品牌"],["核心SKU",num(sku),"含缺价"],["有价SKU",num(priced),missing?num(missing)+" 条缺价":"价格完整"],["全局范围",money(DATA.summary.priceMin)+"-"+money(DATA.summary.priceMax),DATA.summary.biggestCategory+" 样本最多"]].map(([a,b,c])=>`<div class=stat><span>${a}</span><strong>${b}</strong><em>${esc(c)}</em></div>`).join("")}
function renderNav(cats){$("categoryNav").innerHTML=["全部品类",...DATA.categoryOrder].map(name=>`<button class="${state.category===name?"active":""}" data-category="${esc(name)}">${esc(name)}</button>`).join("");$("categoryNav").querySelectorAll("button").forEach(btn=>btn.onclick=()=>{state.category=btn.dataset.category;$("categoryFilter").value=state.category;render()})}
function bandHtml(band){const cls=band.count?"band active":"band";const inner=`<strong>${esc(band.label)}</strong><span>${num(band.count)}款</span><i style="--w:${pct(band.share)}"></i>`;return band.count?`<a class="${cls}" href="${esc(band.link)}">${inner}</a>`:`<span class="${cls}">${inner}</span>`}
function miniBandHtml(band){return band.count?`<a class=mini-band href="${esc(band.link)}"><strong>${esc(band.label)}</strong><span>${num(band.count)}</span></a>`:""}
function brandRow(row){return `<tr><td class=brand-name>${esc(row.brand)}</td><td class=num>${num(row.skuCount)}</td><td class=num>${num(row.pricedCount)}</td><td class=range>${range(row)}</td><td class=num>${money(row.p25)}</td><td class=num>${money(row.median)}</td><td class=num>${money(row.p75)}</td><td>${esc(row.mainBand)}</td><td><div class=brand-bands>${row.bands.map(miniBandHtml).join("")}</div></td><td class=note>${row.missingPriceCount?num(row.missingPriceCount)+" 条缺价未入带":"—"}</td></tr>`}
function categoryHtml(cat){return `<article class=category id="${encodeURIComponent(cat.category)}"><header class=category-head><div><h2>${esc(cat.category)}</h2><p>${esc(cat.comment)}</p></div><div class=head-metrics><div><span>SKU</span><strong>${num(cat.skuCount)}</strong></div><div><span>有价</span><strong>${num(cat.pricedCount)}</strong></div><div><span>P25-P75</span><strong>${money(cat.p25)}-${money(cat.p75)}</strong></div></div></header><div class=band-strip>${cat.bands.map(bandHtml).join("")}</div><div class=table-wrap><table class=price-table><thead><tr><th>品牌</th><th class=num>SKU</th><th class=num>有价</th><th>最低-最高</th><th class=num>P25</th><th class=num>中位</th><th class=num>P75</th><th>主力带</th><th>可点击价格带</th><th>备注</th></tr></thead><tbody>${cat.brands.map(brandRow).join("")}</tbody></table></div></article>`}
function render(){const cats=categories();renderSummary(cats);renderNav(cats);$("categoryList").innerHTML=cats.map(categoryHtml).join("")||'<p class=empty>没有匹配的价格带。</p>'}
init();