const DATA=window.__BRAND_NATIVE_PRICE_DATA__;
const state={brand:"全部品牌"};
const $=id=>document.getElementById(id);
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;")}
function money(v){return Number.isFinite(v)?"¥"+Math.round(v).toLocaleString("zh-CN"):"—"}
function num(v){return Number.isFinite(v)?Math.round(v).toLocaleString("zh-CN"):"—"}
function pct(n,d){return d?Math.round(n/d*100)+"%":"—"}
function priceBand(p){return p.pricedCount?money(p.p25)+"-"+money(p.p75):"—"}
function init(){document.getElementById("generatedAt").textContent=DATA.generatedAtText;document.getElementById("totalRows").textContent=DATA.summary.rowCount.toLocaleString("zh-CN");$("brandFilter").innerHTML=["全部品牌",...DATA.brands.map(b=>b.brand)].map(v=>`<option>${esc(v)}</option>`).join("");$("brandFilter").onchange=e=>{state.brand=e.target.value;render()};render()}
function brandVisible(brand){return state.brand==="全部品牌"||brand.brand===state.brand}
function filteredBrands(){return DATA.brands.filter(brandVisible)}
function renderSummary(brands){const rows=brands.flatMap(b=>b.rows);const priced=rows.filter(r=>Number.isFinite(r.price)).length;const brandsCount=brands.length;const salesRows=rows.filter(r=>Number.isFinite(r.sales)&&r.sales>0).length;const catCount=brands.reduce((s,b)=>s+b.categories.length,0);$("summaryGrid").innerHTML=[["品牌数",num(brandsCount),"当前筛选"],["SKU/SPU",num(rows.length),"去重后全量底表"],["有价格",pct(priced,rows.length),num(priced)+" 条"],["有销量/付款",pct(salesRows,rows.length),num(salesRows)+" 条"],["品牌内品类",num(catCount),"各品牌独立口径"]].map(([a,b,c])=>`<div class=stat><span>${a}</span><strong>${b}</strong><em>${c}</em></div>`).join("")}
function renderNav(brands){$("brandNav").innerHTML=["全部品牌",...brands.map(b=>b.brand)].map(name=>`<button class="${state.brand===name?"active":""}" data-brand="${esc(name)}">${esc(name)}</button>`).join("");$("brandNav").querySelectorAll("button").forEach(btn=>btn.onclick=()=>{state.brand=btn.dataset.brand;$("brandFilter").value=state.brand;render()})}
function categoryRows(brand){const maxCount=Math.max(1,...brand.categories.map(c=>c.count));return brand.categories.map(c=>`<tr><td><span class=tag>${esc(c.label)}</span><br><small>${esc(c.basisSample||"")}</small></td><td class=num>${num(c.count)}</td><td class=num>${num(c.price.pricedCount)}</td><td class=num>${priceBand(c.price)}</td><td class=num>${money(c.price.median)}</td><td class=num>${num(c.salesTotal)}</td><td><div class=bar-track><div class=bar-fill style="width:${Math.max(4,Math.round(c.count/maxCount*100))}%"></div></div></td></tr>`).join("")}
function bars(brand){const max=Math.max(1,...brand.priceBins.map(b=>b.count));return brand.priceBins.map(b=>`<div class=bar-row><span>${esc(b.label)}</span><div class=bar-track><div class=bar-fill style="width:${Math.max(b.count?5:0,Math.round(b.count/max*100))}%"></div></div><strong>${num(b.count)}</strong></div>`).join("")}
function productRows(brand){return brand.topProducts.map((p,i)=>`<div class=product><div><strong>${p.productUrl?`<a href="${esc(p.productUrl)}" target="_blank">${esc(p.title)}</a>`:esc(p.title)}</strong><small>${esc(p.nativeCategory)} ｜ itemId ${esc(p.itemId||"—")}</small></div><div class=price>${money(p.price)}</div><div class=sales>${p.salesText?esc(p.salesText):num(p.sales)}</div><div class=rank>#${i+1}</div></div>`).join("")||"<p class=empty>当前筛选下没有商品。</p>"}
function brandSection(brand){const priceCoverage=brand.rowCount?pct(brand.price.pricedCount,brand.rowCount):"—";const salesCoverage=brand.rowCount?pct(brand.salesRows,brand.rowCount):"—";return `<article class=brand-section id="${esc(brand.slug)}"><header class=brand-head><div><h2>${esc(brand.brand)}</h2><p>${esc(brand.categoryNote)}</p></div><div class=quality><div><span>SKU/SPU</span><strong>${num(brand.rowCount)}</strong></div><div><span>有价格</span><strong class="${brand.price.pricedCount/brand.rowCount<.6?"low":""}">${priceCoverage}</strong></div><div><span>主力带</span><strong>${priceBand(brand.price)}</strong></div></div></header><div class=brand-body><aside class=insights><h3>判断</h3><p>${esc(brand.observation)}</p><div class=mini-metrics><div><span>最低-最高</span><strong>${brand.price.pricedCount?money(brand.price.min)+" / "+money(brand.price.max):"—"}</strong></div><div><span>销量字段</span><strong>${salesCoverage}</strong></div><div><span>中位价</span><strong>${money(brand.price.median)}</strong></div><div><span>品类组</span><strong>${num(brand.categories.length)}</strong></div></div><div class=bars><h3>价格分布</h3>${bars(brand)}</div></aside><div class=detail><section class=category-table><h3>品牌内品类价格带</h3><table><thead><tr><th>品牌品类/系列</th><th class=num>SKU</th><th class=num>有价</th><th class=num>核心价格带</th><th class=num>中位价</th><th class=num>销量字段合计</th><th>规模</th></tr></thead><tbody>${categoryRows(brand)}</tbody></table></section><section class=products><h3>销量/付款字段靠前商品</h3><div class=product-list>${productRows(brand)}</div></section></div></div></article>`}
function render(){const brands=filteredBrands();renderSummary(brands);renderNav(DATA.brands);$("brandSections").innerHTML=brands.map(brandSection).join("")||'<p class=empty>没有匹配的品牌或商品。</p>'}
init();