const DATA=window.__BRAND_NATIVE_PRICE_DATA__;
const state={brand:"全部品牌"};
const $=id=>document.getElementById(id);
let activeModalRows=[];
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;")}
function money(v){return Number.isFinite(v)?"¥"+Math.round(v).toLocaleString("zh-CN"):"—"}
function num(v){return Number.isFinite(v)?Math.round(v).toLocaleString("zh-CN"):"—"}
function pct(n,d){return d?Math.round(n/d*100)+"%":"—"}
function priceBand(p){return p.pricedCount?money(p.p25)+"-"+money(p.p75):"—"}
function init(){document.getElementById("generatedAt").textContent=DATA.generatedAtText;document.getElementById("totalRows").textContent=DATA.summary.rowCount.toLocaleString("zh-CN");$("brandFilter").innerHTML=["全部品牌",...DATA.brands.map(b=>b.brand)].map(v=>`<option>${esc(v)}</option>`).join("");$("brandFilter").onchange=e=>{state.brand=e.target.value;render()};$("modalClose").onclick=closeModal;$("modalBackdrop").onclick=closeModal;$("modalSearch").oninput=renderModalRows;document.addEventListener("keydown",event=>{if(event.key==="Escape")closeModal()});render()}
function brandVisible(brand){return state.brand==="全部品牌"||brand.brand===state.brand}
function filteredBrands(){return DATA.brands.filter(brandVisible)}
function renderSummary(brands){const rows=brands.flatMap(b=>b.rows);const priced=rows.filter(r=>Number.isFinite(r.price)).length;const brandsCount=brands.length;const salesRows=rows.filter(r=>Number.isFinite(r.sales)&&r.sales>0).length;const catCount=brands.reduce((s,b)=>s+b.categories.length,0);$("summaryGrid").innerHTML=[["品牌数",num(brandsCount),"当前筛选"],["SKU/SPU",num(rows.length),"去重后全量底表"],["有价格",pct(priced,rows.length),num(priced)+" 条"],["有销量/付款",pct(salesRows,rows.length),num(salesRows)+" 条"],["品牌内品类",num(catCount),"各品牌独立口径"]].map(([a,b,c])=>`<div class=stat><span>${a}</span><strong>${b}</strong><em>${c}</em></div>`).join("")}
function renderNav(brands){$("brandNav").innerHTML=["全部品牌",...brands.map(b=>b.brand)].map(name=>`<button class="${state.brand===name?"active":""}" data-brand="${esc(name)}">${esc(name)}</button>`).join("");$("brandNav").querySelectorAll("button").forEach(btn=>btn.onclick=()=>{state.brand=btn.dataset.brand;$("brandFilter").value=state.brand;render()})}
function categoryRows(brand){const maxCount=Math.max(1,...brand.categories.map(c=>c.count));return brand.categories.map(c=>`<tr><td><span class=tag>${esc(c.label)}</span><br><small>${esc(c.basisSample||"")}</small></td><td><button class="view-all" data-brand="${esc(brand.brand)}" data-category="${esc(c.label)}">查看全部</button></td><td class=num>${num(c.count)}</td><td class=num>${num(c.price.pricedCount)}</td><td class=num>${priceBand(c.price)}</td><td class=num>${money(c.price.median)}</td><td class=num>${num(c.salesTotal)}</td><td><div class=bar-track><div class=bar-fill style="width:${Math.max(4,Math.round(c.count/maxCount*100))}%"></div></div></td></tr>`).join("")}
function bars(brand){const max=Math.max(1,...brand.priceBins.map(b=>b.count));return brand.priceBins.map(b=>`<div class=bar-row><span>${esc(b.label)}</span><div class=bar-track><div class=bar-fill style="width:${Math.max(b.count?5:0,Math.round(b.count/max*100))}%"></div></div><strong>${num(b.count)}</strong></div>`).join("")}
function productRows(brand){return brand.topProducts.map((p,i)=>`<div class=product><div><strong>${p.productUrl?`<a href="${esc(p.productUrl)}" target="_blank">${esc(p.title)}</a>`:esc(p.title)}</strong><small>${esc(p.nativeCategory)} ｜ itemId ${esc(p.itemId||"—")}</small></div><div class=price>${money(p.price)}</div><div class=sales>${p.salesText?esc(p.salesText):num(p.sales)}</div><div class=rank>#${i+1}</div></div>`).join("")||"<p class=empty>当前筛选下没有商品。</p>"}
function brandSection(brand){const priceCoverage=brand.rowCount?pct(brand.price.pricedCount,brand.rowCount):"—";const salesCoverage=brand.rowCount?pct(brand.salesRows,brand.rowCount):"—";return `<article class=brand-section id="${esc(brand.slug)}"><header class=brand-head><div><h2>${esc(brand.brand)}</h2><p>${esc(brand.categoryNote)}</p></div><div class=quality><div><span>SKU/SPU</span><strong>${num(brand.rowCount)}</strong></div><div><span>有价格</span><strong class="${brand.price.pricedCount/brand.rowCount<.6?"low":""}">${priceCoverage}</strong></div><div><span>主力带</span><strong>${priceBand(brand.price)}</strong></div></div></header><div class=brand-body><aside class=insights><h3>判断</h3><p>${esc(brand.observation)}</p><div class=mini-metrics><div><span>最低-最高</span><strong>${brand.price.pricedCount?money(brand.price.min)+" / "+money(brand.price.max):"—"}</strong></div><div><span>销量字段</span><strong>${salesCoverage}</strong></div><div><span>中位价</span><strong>${money(brand.price.median)}</strong></div><div><span>品类组</span><strong>${num(brand.categories.length)}</strong></div></div><div class=bars><h3>价格分布</h3>${bars(brand)}</div></aside><div class=detail><section class=category-table><h3>品牌内品类价格带</h3><table><thead><tr><th>品牌品类/系列</th><th>明细</th><th class=num>SKU</th><th class=num>有价</th><th class=num>核心价格带</th><th class=num>中位价</th><th class=num>销量字段合计</th><th>规模</th></tr></thead><tbody>${categoryRows(brand)}</tbody></table></section><section class=products><h3>销量/付款字段靠前商品</h3><div class=product-list>${productRows(brand)}</div></section></div></div></article>`}
function bindDetailButtons(){document.querySelectorAll(".view-all").forEach(btn=>{btn.onclick=()=>openCategoryDetail(btn.dataset.brand,btn.dataset.category)})}
function openCategoryDetail(brandName,categoryName){const brand=DATA.brands.find(item=>item.brand===brandName);if(!brand)return;activeModalRows=brand.rows.filter(row=>row.nativeCategory===categoryName).slice().sort((a,b)=>(b.sales||0)-(a.sales||0)||(Number.isFinite(a.price)?a.price:999999)-(Number.isFinite(b.price)?b.price:999999));const priced=activeModalRows.filter(row=>Number.isFinite(row.price)).length;const sales=activeModalRows.filter(row=>Number.isFinite(row.sales)&&row.sales>0).length;$("modalTitle").textContent=`${brandName} · ${categoryName}`;$("modalMeta").textContent=`${activeModalRows.length} 条 SKU/SPU｜${priced} 条有价格｜${sales} 条有销量/付款字段`;$("modalSearch").value="";renderModalRows();$("skuModal").hidden=false;document.body.classList.add("modal-open");setTimeout(()=>$("modalSearch").focus(),0)}
function renderModalRows(){const q=$("modalSearch").value.trim().toLowerCase();const rows=q?activeModalRows.filter(row=>`${row.title} ${row.itemId||""} ${row.skuId||""} ${row.skuSummary||""} ${row.shopName||""}`.toLowerCase().includes(q)):activeModalRows;$("modalCount").textContent=`展示 ${num(rows.length)} / ${num(activeModalRows.length)} 条`;$("skuDetailTable").className="detail-table";$("skuDetailTable").innerHTML=`<thead><tr><th class="detail-title">商品标题</th><th class=num>价格</th><th>销量/付款</th><th>itemId</th><th>SKU摘要</th><th class="link-cell">链接</th></tr></thead><tbody>${rows.map(row=>`<tr><td class="detail-title"><strong>${esc(row.title)}</strong><small>${esc(row.shopName||"—")}｜${esc(row.nativeCategoryBasis||"")}</small></td><td class=num>${money(row.price)}</td><td>${row.salesText?esc(row.salesText):num(row.sales)}</td><td>${esc(row.itemId||"—")}</td><td><small>${esc(row.skuSummary||"—")}</small></td><td class="link-cell">${row.productUrl?`<a href="${esc(row.productUrl)}" target="_blank">打开</a>`:"—"}</td></tr>`).join("")}</tbody>`}
function closeModal(){if($("skuModal")){$("skuModal").hidden=true;document.body.classList.remove("modal-open")}}
function render(){const brands=filteredBrands();renderSummary(brands);renderNav(DATA.brands);$("brandSections").innerHTML=brands.map(brandSection).join("")||'<p class=empty>没有匹配的品牌或商品。</p>';bindDetailButtons()}
init();